// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const clearAllDefaultAgents = `-- name: ClearAllDefaultAgents :exec
UPDATE agents SET is_default = false, updated_at = NOW()
WHERE deleted_at IS NULL AND is_default IS TRUE
`

func (q *Queries) ClearAllDefaultAgents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearAllDefaultAgents)
	return err
}

const countAgents = `-- name: CountAgents :one
SELECT COUNT(*) FROM agents WHERE deleted_at IS NULL
`

func (q *Queries) CountAgents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgentsByName = `-- name: CountAgentsByName :one
SELECT COUNT(*) FROM agents WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAgentsByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentsByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAgentsByNameExcluding = `-- name: CountAgentsByNameExcluding :one
SELECT COUNT(*) FROM agents
WHERE name = $1 AND id != $2 AND deleted_at IS NULL
`

type CountAgentsByNameExcludingParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) CountAgentsByNameExcluding(ctx context.Context, arg CountAgentsByNameExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAgentsByNameExcluding, arg.Name, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (name, soul, is_default, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, name, soul, is_default, created_at, updated_at, deleted_at
`

type CreateAgentParams struct {
	Name      string
	Soul      string
	IsDefault bool
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent, arg.Name, arg.Soul, arg.IsDefault)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Soul,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAgentById = `-- name: GetAgentById :one
SELECT id, name, soul, is_default, created_at, updated_at, deleted_at
FROM agents
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAgentById(ctx context.Context, id uuid.UUID) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentById, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Soul,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, soul, is_default, created_at, updated_at, deleted_at
FROM agents
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAgentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Soul,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentDefault = `-- name: SetAgentDefault :exec
UPDATE agents SET is_default = true, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SetAgentDefault(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setAgentDefault, id)
	return err
}

const setAgentNotDefault = `-- name: SetAgentNotDefault :exec
UPDATE agents SET is_default = false, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SetAgentNotDefault(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setAgentNotDefault, id)
	return err
}

const softDeleteAgent = `-- name: SoftDeleteAgent :exec
UPDATE agents SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAgent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteAgent, id)
	return err
}

const updateAgentFields = `-- name: UpdateAgentFields :exec
UPDATE agents
SET name = $2, soul = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAgentFieldsParams struct {
	ID   uuid.UUID
	Name string
	Soul string
}

func (q *Queries) UpdateAgentFields(ctx context.Context, arg UpdateAgentFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateAgentFields, arg.ID, arg.Name, arg.Soul)
	return err
}
