// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memories (agent_id, content, embedding, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, agent_id, content, created_at, updated_at, deleted_at
`

type CreateMemoryParams struct {
	AgentID   uuid.UUID
	Content   string
	Embedding pgvector_go.Vector
}

type CreateMemoryRow struct {
	ID        uuid.UUID
	AgentID   uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (CreateMemoryRow, error) {
	row := q.db.QueryRowContext(ctx, createMemory, arg.AgentID, arg.Content, arg.Embedding)
	var i CreateMemoryRow
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const fullTextSearchMemories = `-- name: FullTextSearchMemories :many
SELECT id, agent_id, content, created_at, updated_at, deleted_at
FROM memories
WHERE deleted_at IS NULL AND agent_id = $1
  AND to_tsvector('simple', content) @@ plainto_tsquery('simple', $2)
ORDER BY ts_rank(to_tsvector('simple', content), plainto_tsquery('simple', $2)) DESC
LIMIT $3
`

type FullTextSearchMemoriesParams struct {
	AgentID        uuid.UUID
	PlaintoTsquery string
	Limit          int32
}

type FullTextSearchMemoriesRow struct {
	ID        uuid.UUID
	AgentID   uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

func (q *Queries) FullTextSearchMemories(ctx context.Context, arg FullTextSearchMemoriesParams) ([]FullTextSearchMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, fullTextSearchMemories, arg.AgentID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FullTextSearchMemoriesRow
	for rows.Next() {
		var i FullTextSearchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMemoriesByAgent = `-- name: SoftDeleteMemoriesByAgent :exec
UPDATE memories SET deleted_at = NOW()
WHERE agent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMemoriesByAgent(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteMemoriesByAgent, agentID)
	return err
}

const vectorSearchMemories = `-- name: VectorSearchMemories :many
SELECT id, agent_id, content, created_at, updated_at, deleted_at
FROM memories
WHERE deleted_at IS NULL AND agent_id = $1
ORDER BY embedding <=> $2
LIMIT $3
`

type VectorSearchMemoriesParams struct {
	AgentID   uuid.UUID
	Embedding pgvector_go.Vector
	Limit     int32
}

type VectorSearchMemoriesRow struct {
	ID        uuid.UUID
	AgentID   uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

func (q *Queries) VectorSearchMemories(ctx context.Context, arg VectorSearchMemoriesParams) ([]VectorSearchMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, vectorSearchMemories, arg.AgentID, arg.Embedding, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VectorSearchMemoriesRow
	for rows.Next() {
		var i VectorSearchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
