// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const batchCreateMessages = `-- name: BatchCreateMessages :many
INSERT INTO chat_messages (session_id, agent_id, role, content, tool_calls, tool_results,
                           model_id, reasoning_content, provider_specifics, created_at)
SELECT unnest($1::uuid[]),
       unnest($2::uuid[]),
       unnest($3::varchar[]),
       unnest($4::text[]),
       unnest($5::jsonb[]),
       unnest($6::jsonb[]),
       unnest($7::uuid[]),
       unnest($8::text[]),
       unnest($9::jsonb[]),
       unnest($10::timestamptz[])
RETURNING id, session_id, agent_id, role, content, tool_calls, tool_results,
          model_id, reasoning_content, provider_specifics, created_at, deleted_at
`

type BatchCreateMessagesParams struct {
	SessionIds           []uuid.UUID
	AgentIds             []uuid.UUID
	Roles                []string
	Contents             []string
	ToolCallsArr         []json.RawMessage
	ToolResultsArr       []json.RawMessage
	ModelIds             []uuid.UUID
	ReasoningContents    []string
	ProviderSpecificsArr []json.RawMessage
	CreatedAts           []time.Time
}

func (q *Queries) BatchCreateMessages(ctx context.Context, arg BatchCreateMessagesParams) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, batchCreateMessages,
		pq.Array(arg.SessionIds),
		pq.Array(arg.AgentIds),
		pq.Array(arg.Roles),
		pq.Array(arg.Contents),
		pq.Array(arg.ToolCallsArr),
		pq.Array(arg.ToolResultsArr),
		pq.Array(arg.ModelIds),
		pq.Array(arg.ReasoningContents),
		pq.Array(arg.ProviderSpecificsArr),
		pq.Array(arg.CreatedAts),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgentID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolResults,
			&i.ModelID,
			&i.ReasoningContent,
			&i.ProviderSpecifics,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_messages (session_id, agent_id, role, content, tool_calls, tool_results,
                           model_id, reasoning_content, provider_specifics, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
RETURNING id, session_id, agent_id, role, content, tool_calls, tool_results,
          model_id, reasoning_content, provider_specifics, created_at, deleted_at
`

type CreateMessageParams struct {
	SessionID         uuid.UUID
	AgentID           uuid.UUID
	Role              string
	Content           string
	ToolCalls         pqtype.NullRawMessage
	ToolResults       pqtype.NullRawMessage
	ModelID           uuid.UUID
	ReasoningContent  string
	ProviderSpecifics pqtype.NullRawMessage
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.SessionID,
		arg.AgentID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.ToolResults,
		arg.ModelID,
		arg.ReasoningContent,
		arg.ProviderSpecifics,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.AgentID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.ToolResults,
		&i.ModelID,
		&i.ReasoningContent,
		&i.ProviderSpecifics,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDistinctModelIdsBySession = `-- name: GetDistinctModelIdsBySession :many
SELECT DISTINCT model_id
FROM chat_messages
WHERE session_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDistinctModelIdsBySession(ctx context.Context, sessionID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getDistinctModelIdsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var model_id uuid.UUID
		if err := rows.Scan(&model_id); err != nil {
			return nil, err
		}
		items = append(items, model_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesBySession = `-- name: GetMessagesBySession :many
SELECT id, session_id, agent_id, role, content, tool_calls, tool_results,
       model_id, reasoning_content, provider_specifics, created_at, deleted_at
FROM chat_messages
WHERE session_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) GetMessagesBySession(ctx context.Context, sessionID uuid.UUID) ([]ChatMessage, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.AgentID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.ToolResults,
			&i.ModelID,
			&i.ReasoningContent,
			&i.ProviderSpecifics,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessagesByAgent = `-- name: SoftDeleteMessagesByAgent :exec
UPDATE chat_messages SET deleted_at = NOW()
WHERE agent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMessagesByAgent(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteMessagesByAgent, agentID)
	return err
}
