// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	pgvector_go "github.com/pgvector/pgvector-go"
	"github.com/sqlc-dev/pqtype"
)

type Agent struct {
	ID        uuid.UUID
	Name      string
	Soul      string
	IsDefault bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type ChatMessage struct {
	ID                uuid.UUID
	SessionID         uuid.UUID
	AgentID           uuid.UUID
	Role              string
	Content           string
	ToolCalls         pqtype.NullRawMessage
	ToolResults       pqtype.NullRawMessage
	ModelID           uuid.UUID
	ReasoningContent  string
	ProviderSpecifics pqtype.NullRawMessage
	CreatedAt         time.Time
	DeletedAt         sql.NullTime
}

type ChatSession struct {
	ID            uuid.UUID
	AgentID       uuid.UUID
	TokenConsumed int64
	LastUsedModel uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
}

type Memory struct {
	ID        uuid.UUID
	AgentID   uuid.UUID
	Content   string
	Embedding pgvector_go.Vector
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Model struct {
	ID                        uuid.UUID
	ProviderID                uuid.UUID
	Name                      string
	Code                      string
	DefaultModel              bool
	Thinking                  bool
	ThinkingLevels            json.RawMessage
	AnthropicAdaptiveThinking bool
	CreatedAt                 time.Time
	UpdatedAt                 time.Time
	DeletedAt                 sql.NullTime
}

type ModelProvider struct {
	ID        uuid.UUID
	Name      string
	Type      string
	BaseUrl   string
	ApiKey    string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
