// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: models.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const clearDefaultModelExcluding = `-- name: ClearDefaultModelExcluding :exec
UPDATE models SET default_model = false, updated_at = NOW()
WHERE id != $1 AND default_model IS TRUE AND deleted_at IS NULL
`

func (q *Queries) ClearDefaultModelExcluding(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearDefaultModelExcluding, id)
	return err
}

const countModels = `-- name: CountModels :one
SELECT COUNT(*) FROM models WHERE deleted_at IS NULL
`

func (q *Queries) CountModels(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModelsByCode = `-- name: CountModelsByCode :one
SELECT COUNT(*) FROM models
WHERE code = $1 AND provider_id = $2 AND deleted_at IS NULL
`

type CountModelsByCodeParams struct {
	Code       string
	ProviderID uuid.UUID
}

func (q *Queries) CountModelsByCode(ctx context.Context, arg CountModelsByCodeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModelsByCode, arg.Code, arg.ProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModelsByName = `-- name: CountModelsByName :one
SELECT COUNT(*) FROM models
WHERE name = $1 AND provider_id = $2 AND deleted_at IS NULL
`

type CountModelsByNameParams struct {
	Name       string
	ProviderID uuid.UUID
}

func (q *Queries) CountModelsByName(ctx context.Context, arg CountModelsByNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModelsByName, arg.Name, arg.ProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModelsByNameExcluding = `-- name: CountModelsByNameExcluding :one
SELECT COUNT(*) FROM models
WHERE name = $1 AND provider_id = $2 AND id != $3 AND deleted_at IS NULL
`

type CountModelsByNameExcludingParams struct {
	Name       string
	ProviderID uuid.UUID
	ID         uuid.UUID
}

func (q *Queries) CountModelsByNameExcluding(ctx context.Context, arg CountModelsByNameExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModelsByNameExcluding, arg.Name, arg.ProviderID, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countModelsByProvider = `-- name: CountModelsByProvider :one
SELECT COUNT(*) FROM models WHERE provider_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountModelsByProvider(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countModelsByProvider, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO models (provider_id, name, code, default_model, thinking, thinking_levels,
                    anthropic_adaptive_thinking, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, provider_id, name, code, default_model, thinking, thinking_levels,
          anthropic_adaptive_thinking, created_at, updated_at, deleted_at
`

type CreateModelParams struct {
	ProviderID                uuid.UUID
	Name                      string
	Code                      string
	DefaultModel              bool
	Thinking                  bool
	ThinkingLevels            json.RawMessage
	AnthropicAdaptiveThinking bool
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, createModel,
		arg.ProviderID,
		arg.Name,
		arg.Code,
		arg.DefaultModel,
		arg.Thinking,
		arg.ThinkingLevels,
		arg.AnthropicAdaptiveThinking,
	)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Code,
		&i.DefaultModel,
		&i.Thinking,
		&i.ThinkingLevels,
		&i.AnthropicAdaptiveThinking,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCurrentDefaultExcluding = `-- name: GetCurrentDefaultExcluding :one
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE default_model IS TRUE AND id != $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetCurrentDefaultExcluding(ctx context.Context, id uuid.UUID) (Model, error) {
	row := q.db.QueryRowContext(ctx, getCurrentDefaultExcluding, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Code,
		&i.DefaultModel,
		&i.Thinking,
		&i.ThinkingLevels,
		&i.AnthropicAdaptiveThinking,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDefaultModel = `-- name: GetDefaultModel :one
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE default_model IS TRUE AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDefaultModel(ctx context.Context) (Model, error) {
	row := q.db.QueryRowContext(ctx, getDefaultModel)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Code,
		&i.DefaultModel,
		&i.Thinking,
		&i.ThinkingLevels,
		&i.AnthropicAdaptiveThinking,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFirstModel = `-- name: GetFirstModel :one
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetFirstModel(ctx context.Context) (Model, error) {
	row := q.db.QueryRowContext(ctx, getFirstModel)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Code,
		&i.DefaultModel,
		&i.Thinking,
		&i.ThinkingLevels,
		&i.AnthropicAdaptiveThinking,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getModelById = `-- name: GetModelById :one
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetModelById(ctx context.Context, id uuid.UUID) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModelById, id)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Code,
		&i.DefaultModel,
		&i.Thinking,
		&i.ThinkingLevels,
		&i.AnthropicAdaptiveThinking,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getModelByNameAndProvider = `-- name: GetModelByNameAndProvider :one
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE name = $1 AND provider_id = $2 AND deleted_at IS NULL
`

type GetModelByNameAndProviderParams struct {
	Name       string
	ProviderID uuid.UUID
}

func (q *Queries) GetModelByNameAndProvider(ctx context.Context, arg GetModelByNameAndProviderParams) (Model, error) {
	row := q.db.QueryRowContext(ctx, getModelByNameAndProvider, arg.Name, arg.ProviderID)
	var i Model
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Code,
		&i.DefaultModel,
		&i.Thinking,
		&i.ThinkingLevels,
		&i.AnthropicAdaptiveThinking,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getModelsByProvider = `-- name: GetModelsByProvider :many
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE provider_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetModelsByProvider(ctx context.Context, providerID uuid.UUID) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, getModelsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Code,
			&i.DefaultModel,
			&i.Thinking,
			&i.ThinkingLevels,
			&i.AnthropicAdaptiveThinking,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListModelsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Code,
			&i.DefaultModel,
			&i.Thinking,
			&i.ThinkingLevels,
			&i.AnthropicAdaptiveThinking,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByIds = `-- name: ListModelsByIds :many
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

func (q *Queries) ListModelsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModelsByIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Code,
			&i.DefaultModel,
			&i.Thinking,
			&i.ThinkingLevels,
			&i.AnthropicAdaptiveThinking,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelsByProvider = `-- name: ListModelsByProvider :many
SELECT id, provider_id, name, code, default_model, thinking, thinking_levels,
       anthropic_adaptive_thinking, created_at, updated_at, deleted_at
FROM models
WHERE provider_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListModelsByProviderParams struct {
	ProviderID uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListModelsByProvider(ctx context.Context, arg ListModelsByProviderParams) ([]Model, error) {
	rows, err := q.db.QueryContext(ctx, listModelsByProvider, arg.ProviderID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Model
	for rows.Next() {
		var i Model
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Code,
			&i.DefaultModel,
			&i.Thinking,
			&i.ThinkingLevels,
			&i.AnthropicAdaptiveThinking,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setModelAsDefault = `-- name: SetModelAsDefault :exec
UPDATE models SET default_model = true, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SetModelAsDefault(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setModelAsDefault, id)
	return err
}

const setModelDefaultFalse = `-- name: SetModelDefaultFalse :exec
UPDATE models SET default_model = false, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SetModelDefaultFalse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setModelDefaultFalse, id)
	return err
}

const softDeleteModel = `-- name: SoftDeleteModel :exec
UPDATE models SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteModel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteModel, id)
	return err
}

const softDeleteModelsByProvider = `-- name: SoftDeleteModelsByProvider :exec
UPDATE models SET deleted_at = NOW()
WHERE provider_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteModelsByProvider(ctx context.Context, providerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteModelsByProvider, providerID)
	return err
}

const updateModelFields = `-- name: UpdateModelFields :exec
UPDATE models
SET name = $2, thinking = $3, thinking_levels = $4,
    anthropic_adaptive_thinking = $5, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateModelFieldsParams struct {
	ID                        uuid.UUID
	Name                      string
	Thinking                  bool
	ThinkingLevels            json.RawMessage
	AnthropicAdaptiveThinking bool
}

func (q *Queries) UpdateModelFields(ctx context.Context, arg UpdateModelFieldsParams) error {
	_, err := q.db.ExecContext(ctx, updateModelFields,
		arg.ID,
		arg.Name,
		arg.Thinking,
		arg.ThinkingLevels,
		arg.AnthropicAdaptiveThinking,
	)
	return err
}
