// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countProviders = `-- name: CountProviders :one
SELECT COUNT(*) FROM model_providers WHERE deleted_at IS NULL
`

func (q *Queries) CountProviders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProvidersByName = `-- name: CountProvidersByName :one
SELECT COUNT(*) FROM model_providers WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProvidersByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProvidersByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProvidersByNameAndType = `-- name: CountProvidersByNameAndType :one
SELECT COUNT(*) FROM model_providers WHERE name = $1 AND type = $2 AND deleted_at IS NULL
`

type CountProvidersByNameAndTypeParams struct {
	Name string
	Type string
}

func (q *Queries) CountProvidersByNameAndType(ctx context.Context, arg CountProvidersByNameAndTypeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProvidersByNameAndType, arg.Name, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProvidersByNameExcluding = `-- name: CountProvidersByNameExcluding :one
SELECT COUNT(*) FROM model_providers
WHERE name = $1 AND id != $2 AND deleted_at IS NULL
`

type CountProvidersByNameExcludingParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) CountProvidersByNameExcluding(ctx context.Context, arg CountProvidersByNameExcludingParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProvidersByNameExcluding, arg.Name, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO model_providers (name, type, base_url, api_key, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, name, type, base_url, api_key, created_at, updated_at, deleted_at
`

type CreateProviderParams struct {
	Name    string
	Type    string
	BaseUrl string
	ApiKey  string
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (ModelProvider, error) {
	row := q.db.QueryRowContext(ctx, createProvider,
		arg.Name,
		arg.Type,
		arg.BaseUrl,
		arg.ApiKey,
	)
	var i ModelProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProviderById = `-- name: GetProviderById :one
SELECT id, name, type, base_url, api_key, created_at, updated_at, deleted_at
FROM model_providers
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProviderById(ctx context.Context, id uuid.UUID) (ModelProvider, error) {
	row := q.db.QueryRowContext(ctx, getProviderById, id)
	var i ModelProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
SELECT id, name, type, base_url, api_key, created_at, updated_at, deleted_at
FROM model_providers
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (ModelProvider, error) {
	row := q.db.QueryRowContext(ctx, getProviderByName, name)
	var i ModelProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, type, base_url, api_key, created_at, updated_at, deleted_at
FROM model_providers
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListProvidersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListProviders(ctx context.Context, arg ListProvidersParams) ([]ModelProvider, error) {
	rows, err := q.db.QueryContext(ctx, listProviders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelProvider
	for rows.Next() {
		var i ModelProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BaseUrl,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByIds = `-- name: ListProvidersByIds :many
SELECT id, name, type, base_url, api_key, created_at, updated_at, deleted_at
FROM model_providers
WHERE id = ANY($1::uuid[]) AND deleted_at IS NULL
`

func (q *Queries) ListProvidersByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]ModelProvider, error) {
	rows, err := q.db.QueryContext(ctx, listProvidersByIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelProvider
	for rows.Next() {
		var i ModelProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BaseUrl,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProvider = `-- name: SoftDeleteProvider :exec
UPDATE model_providers SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteProvider, id)
	return err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE model_providers
SET name = $2, type = $3, base_url = $4, api_key = $5, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, type, base_url, api_key, created_at, updated_at, deleted_at
`

type UpdateProviderParams struct {
	ID      uuid.UUID
	Name    string
	Type    string
	BaseUrl string
	ApiKey  string
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (ModelProvider, error) {
	row := q.db.QueryRowContext(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.BaseUrl,
		arg.ApiKey,
	)
	var i ModelProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
