// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BatchCreateMessages(ctx context.Context, arg BatchCreateMessagesParams) ([]ChatMessage, error)
	ClearAllDefaultAgents(ctx context.Context) error
	ClearDefaultModelExcluding(ctx context.Context, id uuid.UUID) error
	CountAgents(ctx context.Context) (int64, error)
	CountAgentsByName(ctx context.Context, name string) (int64, error)
	CountAgentsByNameExcluding(ctx context.Context, arg CountAgentsByNameExcludingParams) (int64, error)
	CountModels(ctx context.Context) (int64, error)
	CountModelsByCode(ctx context.Context, arg CountModelsByCodeParams) (int64, error)
	CountModelsByName(ctx context.Context, arg CountModelsByNameParams) (int64, error)
	CountModelsByNameExcluding(ctx context.Context, arg CountModelsByNameExcludingParams) (int64, error)
	CountModelsByProvider(ctx context.Context, providerID uuid.UUID) (int64, error)
	CountProviders(ctx context.Context) (int64, error)
	CountProvidersByName(ctx context.Context, name string) (int64, error)
	CountProvidersByNameAndType(ctx context.Context, arg CountProvidersByNameAndTypeParams) (int64, error)
	CountProvidersByNameExcluding(ctx context.Context, arg CountProvidersByNameExcludingParams) (int64, error)
	CountSessions(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (CreateMemoryRow, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (ChatMessage, error)
	CreateModel(ctx context.Context, arg CreateModelParams) (Model, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (ModelProvider, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (ChatSession, error)
	FullTextSearchMemories(ctx context.Context, arg FullTextSearchMemoriesParams) ([]FullTextSearchMemoriesRow, error)
	GetAgentById(ctx context.Context, id uuid.UUID) (Agent, error)
	GetCurrentDefaultExcluding(ctx context.Context, id uuid.UUID) (Model, error)
	GetDefaultModel(ctx context.Context) (Model, error)
	GetDistinctModelIdsBySession(ctx context.Context, sessionID uuid.UUID) ([]uuid.UUID, error)
	GetFirstModel(ctx context.Context) (Model, error)
	GetLastSession(ctx context.Context) (ChatSession, error)
	GetLastSessionByAgent(ctx context.Context, agentID uuid.UUID) (ChatSession, error)
	GetMessagesBySession(ctx context.Context, sessionID uuid.UUID) ([]ChatMessage, error)
	GetModelById(ctx context.Context, id uuid.UUID) (Model, error)
	GetModelByNameAndProvider(ctx context.Context, arg GetModelByNameAndProviderParams) (Model, error)
	GetModelsByProvider(ctx context.Context, providerID uuid.UUID) ([]Model, error)
	GetProviderById(ctx context.Context, id uuid.UUID) (ModelProvider, error)
	GetProviderByName(ctx context.Context, name string) (ModelProvider, error)
	GetSessionById(ctx context.Context, id uuid.UUID) (ChatSession, error)
	ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error)
	ListModels(ctx context.Context, arg ListModelsParams) ([]Model, error)
	ListModelsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Model, error)
	ListModelsByProvider(ctx context.Context, arg ListModelsByProviderParams) ([]Model, error)
	ListProviders(ctx context.Context, arg ListProvidersParams) ([]ModelProvider, error)
	ListProvidersByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]ModelProvider, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]ChatSession, error)
	SetAgentDefault(ctx context.Context, id uuid.UUID) error
	SetAgentNotDefault(ctx context.Context, id uuid.UUID) error
	SetModelAsDefault(ctx context.Context, id uuid.UUID) error
	SetModelDefaultFalse(ctx context.Context, id uuid.UUID) error
	SoftDeleteAgent(ctx context.Context, id uuid.UUID) error
	SoftDeleteMemoriesByAgent(ctx context.Context, agentID uuid.UUID) error
	SoftDeleteMessagesByAgent(ctx context.Context, agentID uuid.UUID) error
	SoftDeleteModel(ctx context.Context, id uuid.UUID) error
	SoftDeleteModelsByProvider(ctx context.Context, providerID uuid.UUID) error
	SoftDeleteProvider(ctx context.Context, id uuid.UUID) error
	SoftDeleteSessionsByAgent(ctx context.Context, agentID uuid.UUID) error
	UpdateAgentFields(ctx context.Context, arg UpdateAgentFieldsParams) error
	UpdateModelFields(ctx context.Context, arg UpdateModelFieldsParams) error
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (ModelProvider, error)
	UpdateSessionTokenAndModel(ctx context.Context, arg UpdateSessionTokenAndModelParams) error
	VectorSearchMemories(ctx context.Context, arg VectorSearchMemoriesParams) ([]VectorSearchMemoriesRow, error)
}

var _ Querier = (*Queries)(nil)
