// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) FROM chat_sessions WHERE deleted_at IS NULL
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO chat_sessions (agent_id, last_used_model, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
RETURNING id, agent_id, token_consumed, last_used_model, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	AgentID       uuid.UUID
	LastUsedModel uuid.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.AgentID, arg.LastUsedModel)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenConsumed,
		&i.LastUsedModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLastSession = `-- name: GetLastSession :one
SELECT id, agent_id, token_consumed, last_used_model, created_at, updated_at, deleted_at
FROM chat_sessions
WHERE deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLastSession(ctx context.Context) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getLastSession)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenConsumed,
		&i.LastUsedModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLastSessionByAgent = `-- name: GetLastSessionByAgent :one
SELECT id, agent_id, token_consumed, last_used_model, created_at, updated_at, deleted_at
FROM chat_sessions
WHERE agent_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetLastSessionByAgent(ctx context.Context, agentID uuid.UUID) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getLastSessionByAgent, agentID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenConsumed,
		&i.LastUsedModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, agent_id, token_consumed, last_used_model, created_at, updated_at, deleted_at
FROM chat_sessions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSessionById(ctx context.Context, id uuid.UUID) (ChatSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionById, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.TokenConsumed,
		&i.LastUsedModel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, agent_id, token_consumed, last_used_model, created_at, updated_at, deleted_at
FROM chat_sessions
WHERE deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT $1 OFFSET $2
`

type ListSessionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ChatSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatSession
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.TokenConsumed,
			&i.LastUsedModel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSessionsByAgent = `-- name: SoftDeleteSessionsByAgent :exec
UPDATE chat_sessions SET deleted_at = NOW()
WHERE agent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSessionsByAgent(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteSessionsByAgent, agentID)
	return err
}

const updateSessionTokenAndModel = `-- name: UpdateSessionTokenAndModel :exec
UPDATE chat_sessions
SET token_consumed = $2, last_used_model = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateSessionTokenAndModelParams struct {
	ID            uuid.UUID
	TokenConsumed int64
	LastUsedModel uuid.UUID
}

func (q *Queries) UpdateSessionTokenAndModel(ctx context.Context, arg UpdateSessionTokenAndModelParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTokenAndModel, arg.ID, arg.TokenConsumed, arg.LastUsedModel)
	return err
}
