// Command generate emits TypeScript DTOs from the actual Go wire types.
package main

import (
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/masteryyh/agenty-core/pkg/domain/conversation"
	"github.com/masteryyh/agenty-core/pkg/domain/shared"
	"github.com/masteryyh/agenty-inspector/internal/inspection"
)

var definitions = map[string]string{}

func main() {
	types := []any{
		inspection.System{},
		inspection.SessionEntry{},
		inspection.Detail{},
		inspection.Record{},
		inspection.RecordDetail{},
		inspection.MessageNode{},
		inspection.ContextView{},
		inspection.Diagnostic{},
	}
	blocks := []conversation.ContentBlock{
		conversation.TextBlock{},
		conversation.ReasoningBlock{},
		conversation.ToolUseBlock{},
		conversation.ToolResultBlock{},
		conversation.ShellCallBlock{},
		conversation.ShellCallOutputBlock{},
		conversation.ApplyPatchCallBlock{},
		conversation.ImageBlock{},
	}

	names := []string{}
	for _, block := range blocks {
		t := reflect.TypeOf(block)
		name := typeName(t)
		definitions[name] = strings.Replace(definitions[name], "{\n", "{\n    type: \""+string(block.BlockType())+"\";\n", 1)
		names = append(names, name)
	}
	for _, value := range types {
		typeName(reflect.TypeOf(value))
	}

	var output strings.Builder
	output.WriteString("// Generated by go run ./cmd/generate. Do not edit.\n")
	output.WriteString("export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n")
	output.WriteString("export type ContentBlock = ")
	output.WriteString(strings.Join(names, " | "))
	output.WriteString(";\n")
	output.WriteString("export interface Page<T> { items: T[]; total: number; nextOffset: number | null; revision: string }\n\n")
	keys := []string{}
	for name := range definitions {
		keys = append(keys, name)
	}
	sort.Strings(keys)
	for _, name := range keys {
		output.WriteString(definitions[name])
		output.WriteString("\n")
	}
	if _, err := os.Stdout.WriteString(output.String()); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func typeName(t reflect.Type) string {
	switch t {
	case reflect.TypeFor[time.Time](), reflect.TypeFor[uuid.UUID]():
		return "string"
	case reflect.TypeFor[shared.RawJSON]():
		return "JsonValue"
	case reflect.TypeFor[conversation.Content]():
		return "ContentBlock[]"
	}

	switch t.Kind() {
	case reflect.Pointer:
		return typeName(t.Elem()) + " | null"
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int64, reflect.Uint64, reflect.Float64:
		return "number"
	case reflect.Slice:
		return "(" + typeName(t.Elem()) + ")[]"
	case reflect.Map:
		return "{ [key: string]: " + typeName(t.Elem()) + " }"
	case reflect.Interface:
		return "JsonValue"
	case reflect.Struct:
		name := t.Name()
		if _, ok := definitions[name]; ok {
			return name
		}
		definitions[name] = ""
		var body strings.Builder
		body.WriteString("export interface ")
		body.WriteString(name)
		body.WriteString(" {\n")
		for field := range t.Fields() {
			tag := strings.Split(field.Tag.Get("json"), ",")
			if !field.IsExported() || tag[0] == "-" {
				continue
			}
			key := tag[0]
			if key == "" {
				key = field.Name
			}
			optional := ""
			if len(tag) > 1 && tag[1] == "omitempty" {
				optional = "?"
			}
			body.WriteString("    ")
			body.WriteString(key)
			body.WriteString(optional)
			body.WriteString(": ")
			body.WriteString(typeName(field.Type))
			body.WriteString(";\n")
		}
		definitions[name] = body.String() + "}\n"
		return name
	default:
		panic("unsupported wire type: " + t.String())
	}
}
