// Generated by go run ./cmd/generate. Do not edit.
export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type ContentBlock = TextBlock | ReasoningBlock | ToolUseBlock | ToolResultBlock | ShellCallBlock | ShellCallOutputBlock | ApplyPatchCallBlock | ImageBlock;
export interface Page<T> { items: T[]; total: number; nextOffset: number | null; revision: string }

export interface ApplyPatchCallBlock {
    type: "apply_patch_call";
    id?: string;
    callId: string;
    source: string;
    operation?: ApplyPatchOperation | null;
    patch?: string;
}

export interface ApplyPatchOperation {
    type: string;
    path: string;
    diff?: string;
    moveTo?: string;
}

export interface ContextMessage {
    message: Message;
    kind: string;
    sources: (SourceRef)[];
}

export interface ContextView {
    revision: string;
    atRecord: string;
    replayedThrough: number;
    complete: boolean;
    before: (ContextMessage)[];
    after: (ContextMessage)[];
}

export interface Detail {
    entry: SessionEntry;
    revision: string;
    sessionId: string;
    title: string | null;
    agentCode: string;
    currentModel: ModelRef | null;
    cwd: string | null;
    contextWindow: number;
    reasoningEffort: string;
    rounds: (RoundNode)[];
    recordCount: number;
    messageCount: number;
    hiddenCount: number;
    replayedThrough: number;
    complete: boolean;
    diagnostics: (Diagnostic)[];
    tools: (ToolRelation)[];
}

export interface Diagnostic {
    code: string;
    severity: string;
    message: string;
    source: SourceRef;
}

export interface Envelope {
    type: string;
    seq: number;
    payload: JsonValue;
    wroteAt: string;
}

export interface ImageBlock {
    type: "image";
    mimeType: string;
    data?: string;
    uri?: string;
}

export interface Message {
    id: string;
    roundId: string;
    role: string;
    visibility?: string;
    content: ContentBlock[];
    model?: ModelRef | null;
    usage?: TokenUsage | null;
    metadata?: { [key: string]: JsonValue };
    createdAt: string;
}

export interface MessageNode {
    message: Message;
    source: SourceRef;
}

export interface ModelRef {
    providerCode: string;
    modelCode: string;
}

export interface ReasoningBlock {
    type: "reasoning";
    reasoning: string;
    signature?: string;
    redacted?: boolean;
    extra?: JsonValue;
}

export interface Record {
    id: string;
    line: number;
    offset: number;
    length: number;
    terminated: boolean;
    seq: number;
    type: string;
    wroteAt: string;
    roundId?: string;
    summary: string;
    error?: string;
    applied: boolean;
}

export interface RecordDetail {
    rawBase64?: string;
    record: Record;
    raw: string;
    envelope: Envelope | null;
}

export interface RoundNode {
    id: string;
    sequence: number;
    status: string;
    model: ModelRef;
    reasoningEffort: string;
    contextWindow: number;
    cwd: string | null;
    startedAt: string;
    endedAt: string | null;
    usage: TokenUsage;
    error: string | null;
    messageCount: number;
    source: SourceRef;
}

export interface SessionEntry {
    issueCount: number;
    id: string;
    sessionId: string;
    path: string;
    title: string;
    agent: string;
    model: string;
    updatedAt: string;
    size: number;
    revision: string;
    error?: string;
}

export interface ShellCallBlock {
    type: "shell_call";
    id?: string;
    callId: string;
    commands: (string)[];
    timeoutMs?: number;
    maxOutputLength?: number;
}

export interface ShellCallOutputBlock {
    type: "shell_call_output";
    callId: string;
    maxOutputLength: number;
    openAINative?: boolean | null;
    output: (ShellCommandOutput)[];
}

export interface ShellCommandOutput {
    stdout: string;
    stderr: string;
    outcome: ShellOutcome;
}

export interface ShellOutcome {
    type: string;
    exitCode?: number | null;
}

export interface SourceRef {
    recordId: string;
    line: number;
    seq: number;
    contentPath?: string;
}

export interface System {
    agents: (string)[];
    models: (string)[];
    dataDir: string;
    sessionsDir: string;
    readOnly: boolean;
    scanning: boolean;
    error?: string;
    generation: number;
    sessionCount: number;
    maxTranscriptBytes: number;
    version: string;
}

export interface TextBlock {
    type: "text";
    text: string;
}

export interface TokenUsage {
    input: number;
    output: number;
    cachedRead?: number;
    cacheWrite?: number;
    reasoning?: number;
    total: number;
}

export interface ToolRelation {
    id: string;
    name: string;
    roundId: string;
    calls: (SourceRef)[];
    results: (SourceRef)[];
    status: string;
}

export interface ToolResultBlock {
    type: "tool_result";
    toolUseId: string;
    content: ContentBlock[];
    isError?: boolean;
}

export interface ToolUseBlock {
    type: "tool_use";
    id: string;
    name: string;
    input: JsonValue;
}

